const Map<String, String> ar = {
  'app_name': 'تطبيق الفواتير',
  'invoices': 'الفواتير',
  'create_invoice': 'إنشاء فاتورة',
  'customers': 'العملاء',
  'shop_info': 'معلومات المتجر',
  'settings': 'الإعدادات',
  'business_settings': 'إعدادات العمل',
  'general_settings': 'الإعدادات العامة',
  'invoice_settings': 'إعدادات الفاتورة',
  'pdf_settings': 'إعدادات PDF',
  'backup_settings': 'النسخ الاحتياطي',
  'save_settings': 'حفظ الإعدادات',
  'business_name': 'اسم العمل',
  'default_currency': 'العملة الافتراضية',
  'currency_symbol': 'رمز العملة',
  'currency_position': 'مكان رمز العملة',
  'decimal_digits': 'عدد المنازل العشرية',
  'language': 'اللغة',
  'theme_mode': 'وضع المظهر',
  'invoice_prefix': 'بادئة الفاتورة',
  'starting_invoice_number': 'رقم البداية',
  'auto_increment_enabled': 'تفعيل الترقيم التلقائي',
  'default_tax': 'نسبة الضريبة الافتراضية %',
  'default_discount': 'نسبة الخصم الافتراضية %',
  'notes_template': 'قالب الملاحظات',
  'payment_instructions': 'تعليمات الدفع',
  'show_logo_pdf': 'إظهار الشعار في PDF',
  'show_customer_notes': 'إظهار ملاحظات العميل',
  'show_footer': 'إظهار التذييل',
  'default_pdf_theme': 'قالب PDF الافتراضي',
  'paper_size': 'حجم الورق',
  'font_size_scale': 'مقياس حجم الخط',
  'compact_mode': 'الوضع المضغوط',
  'export_backup': 'تصدير نسخة احتياطية',
  'import_backup': 'استيراد نسخة احتياطية',
  'paste_json_fallback': 'لصق JSON احتياطي',
  'clear_all_local_data': 'مسح كل البيانات المحلية',
  'reset_settings': 'إعادة ضبط الإعدادات',
  'exporting': 'جاري التصدير...',
  'importing': 'جاري الاستيراد...',
  'clearing': 'جاري المسح...',
  'resetting': 'جاري إعادة الضبط...',
  'save_pdf': 'حفظ PDF',
  'share_pdf': 'مشاركة PDF',
  'print_pdf': 'طباعة PDF',
  'open_saved_pdf': 'فتح ملف PDF المحفوظ',
  'modern': 'حديث',
  'minimal': 'بسيط',
  'dark': 'داكن',
  'thermal': 'حراري',
  'a4': 'A4',
  'cancel': 'إلغاء',
  'import': 'استيراد',
  'open': 'فتح',
  'save': 'حفظ',
  'delete': 'حذف',
  'edit': 'تعديل',
  'view': 'عرض',
  'duplicate': 'تكرار',
  'change': 'تغيير',
  'draft': 'مسودة',
  'saved': 'محفوظة',
  'paid': 'مدفوعة',
  'overdue': 'متأخرة',
  'cancelled': 'ملغاة',
  'all': 'الكل',
  'preview': 'معاينة',
  'preview_pdf': 'معاينة PDF',
  'invoice': 'فاتورة',
  'receipt': 'إيصال',
  'customer': 'عميل',
  'customer_filter': 'العميل',
  'customer_name': 'اسم العميل',
  'full_name': 'الاسم الكامل',
  'phone': 'الهاتف',
  'alternative_phone': 'هاتف بديل',
  'email': 'البريد الإلكتروني',
  'address': 'العنوان',
  'city': 'المدينة',
  'notes': 'ملاحظات',
  'created_date': 'تاريخ الإنشاء',
  'shop_information': 'معلومات المتجر',
  'shop_logo': 'الشعار',
  'shop_cover': 'الغلاف',
  'shop_name': 'اسم المتجر',
  'owner_name': 'اسم المالك',
  'phone_number': 'رقم الهاتف',
  'tax_number': 'الرقم الضريبي',
  'tax_number_value': 'الرقم الضريبي: @value',
  'currency': 'العملة',
  'currency_code': 'رمز العملة النصي',
  'custom_currency': 'عملة مخصصة',
  'save_shop_information': 'حفظ معلومات المتجر',
  'logo_image_path': 'مسار صورة الشعار',
  'choose_image': 'اختيار صورة',
  'use_default_image': 'استخدام الافتراضي',
  'use_placeholder_logo': 'استخدام شعار افتراضي',
  'edit_image': 'تعديل الصورة',
  'crop': 'قص',
  'transform': 'التحريك والتدوير',
  'background': 'الخلفية',
  'rotate_left': 'تدوير لليسار',
  'rotate_right': 'تدوير لليمين',
  'reset_transform': 'إعادة ضبط التحويل',
  'free': 'حر',
  'circle': 'دائري',
  'transparent': 'شفاف',
  'black': 'أسود',
  'white': 'أبيض',
  'gold': 'ذهبي',
  'darkGold': 'ذهبي داكن',
  'blue': 'أزرق',
  'search_customers': 'بحث في العملاء',
  'no_customers_yet': 'لا يوجد عملاء بعد',
  'create_customers_message':
      'أنشئ العملاء مرة واحدة ثم أعد استخدامها في الفواتير.',
  'create_customer': 'إنشاء عميل',
  'customer_details': 'تفاصيل العميل',
  'customer_not_found': 'العميل غير موجود',
  'invoice_history': 'سجل الفواتير',
  'save_customer': 'حفظ العميل',
  'new_customer': 'عميل جديد',
  'edit_customer': 'تعديل العميل',
  'invoice_details': 'تفاصيل الفاتورة',
  'invoice_not_found': 'الفاتورة غير موجودة',
  'no_invoices_yet': 'لا توجد فواتير بعد',
  'create_invoice_message': 'أنشئ أول فاتورة وتابعها هنا.',
  'search_invoice_customer': 'بحث برقم الفاتورة أو العميل',
  'filters': 'الفلاتر',
  'min_price': 'أقل سعر',
  'max_price': 'أعلى سعر',
  'reset_filters': 'إعادة تعيين الفلاتر',
  'number': 'الرقم',
  'date': 'التاريخ',
  'date_from': 'التاريخ من',
  'date_to': 'التاريخ إلى',
  'select_date': 'اختر التاريخ',
  'total': 'الإجمالي',
  'status': 'الحالة',
  'actions': 'الإجراءات',
  'export_pdf': 'تصدير PDF',
  'subtotal': 'المجموع الفرعي',
  'discount': 'الخصم',
  'tax': 'الضريبة',
  'final_total': 'الإجمالي النهائي',
  'one_time_customer': 'عميل لهذه الفاتورة فقط',
  'use_only_invoice': 'استخدام في هذه الفاتورة فقط',
  'create_customer_dialog': 'إنشاء عميل',
  'save_permanently': 'حفظ دائم',
  'product_name': 'اسم المنتج',
  'product_image_path': 'مسار صورة المنتج',
  'quantity': 'الكمية',
  'qty': 'الكمية',
  'unit_price': 'سعر الوحدة',
  'save_product': 'حفظ المنتج',
  'save_invoice': 'حفظ الفاتورة',
  'new_invoice': 'فاتورة جديدة',
  'editing_invoice': 'تعديل فاتورة',
  'invoice_workspace_hint': 'أنشئ وعاين وصدّر فاتورة احترافية.',
  'business_details_on_invoices': 'بيانات العمل التي تظهر على الفواتير',
  'select_customer': 'اختر العميل',
  'customer_address': 'عنوان العميل',
  'quick_create': 'إنشاء سريع',
  'products': 'المنتجات',
  'products_section_hint': 'أضف البنود مع الكميات والأسعار',
  'add_product': 'إضافة منتج',
  'no_products': 'لا توجد منتجات',
  'add_first_product_message': 'أضف أول منتج للبدء في إنشاء الفاتورة.',
  'image': 'الصورة',
  'product': 'المنتج',
  'edit_product': 'تعديل المنتج',
  'delete_product': 'حذف المنتج',
  'invoice_notes': 'ملاحظات الفاتورة',
  'adjustments': 'التعديلات',
  'adjustments_hint': 'قيم الخصم والضريبة تحدّث الإجمالي مباشرة',
  'invoice_totals': 'إجماليات الفاتورة',
  'live_calculation_summary': 'ملخص الحساب المباشر',
  'select_customer_dialog': 'اختر العميل',
  'recent_customers': 'آخر العملاء',
  'no_matching_customers': 'لا توجد نتائج مطابقة',
  'try_different_customer_search': 'جرّب اسماً أو هاتفاً أو مدينة مختلفة.',
  'pdf_preview': 'معاينة PDF',
  'pdf_preview_title': 'معاينة PDF - @number',
  'pdf_saved': 'تم حفظ PDF',
  'save_invoice_storage_question': 'هل تريد حفظ هذه الفاتورة في التخزين؟',
  'do_not_save': 'لا تحفظ',
  'save_invoice_storage': 'حفظ الفاتورة',
  'no_file': 'لا يوجد ملف',
  'save_pdf_first': 'احفظ ملف PDF أولاً.',
  'import_backup_json': 'استيراد JSON للنسخة الاحتياطية',
  'paste_backup_json_here': 'الصق JSON النسخة الاحتياطية هنا',
  'clear_all_local_data_question': 'مسح كل البيانات المحلية؟',
  'clear_all_local_data_warning':
      'سيتم حذف العملاء والفواتير ومعلومات المتجر والإعدادات.',
  'clear_data': 'مسح البيانات',
  'reset_settings_question': 'إعادة ضبط الإعدادات؟',
  'reset_settings_warning': 'سيتم استعادة إعدادات العمل الافتراضية.',
  'reset': 'إعادة ضبط',
  'owner': 'المالك',
  'local_account': 'حساب محلي',
  'clear_search': 'مسح البحث',
  'clear': 'مسح',
  'billing_workspace': 'مساحة الفوترة',
  'bill_to': 'فاتورة إلى',
  'invoice_details_pdf': 'تفاصيل الفاتورة',
  'payment': 'الدفع',
  'thank_you': 'شكراً لتعاملكم معنا.',
  'page_of': 'صفحة @page من @pages',
  'save_customer_choice':
      'هل تريد حفظ هذا العميل دائماً أم استخدامه في هذه الفاتورة فقط؟',
  'temporary_customer': 'عميل مؤقت',
  'temporary_customer_message':
      'يمكن استبدال العميل المؤقت أو حفظه كعميل جديد.',
  'customer_required': 'بيانات العميل مطلوبة.',
  'add_products': 'إضافة منتجات',
  'product_required': 'يجب إضافة منتج واحد على الأقل للفاتورة.',
  'invoice_saved_message': 'تم حفظ الفاتورة @number.',
  'draft_saved': 'تم حفظ المسودة',
  'draft_saved_message': 'مسودة الفاتورة متاحة محلياً.',
  'business_settings_saved': 'تم تحديث إعدادات العمل.',
  'quick_setup': 'الإعداد السريع',
  'apply_default_store_information': 'تطبيق معلومات المتجر الافتراضية',
  'apply_default_store_information_question':
      'هل تريد تطبيق معلومات المتجر الافتراضية لغانم للإنارة؟',
  'apply': 'تطبيق',
  'applying': 'جاري التطبيق...',
  'default_business_profile_applied': 'تم تطبيق معلومات المتجر الافتراضية.',
  'preview_default_invoice': 'معاينة الفاتورة الافتراضية',
  'unsaved_settings_title': 'تعديلات غير محفوظة',
  'unsaved_settings_message':
      'هل تريد حفظ آخر تعديلات الإعدادات؟ سيتم تجاهلها إذا خرجت.',
  'discard': 'تجاهل',
  'export_backup_title': 'تصدير نسخة احتياطية',
  'backup_exported': 'تم تصدير النسخة الاحتياطية',
  'import_backup_title': 'استيراد نسخة احتياطية',
  'backup_imported': 'تم استيراد النسخة الاحتياطية',
  'backup_imported_message': 'تمت استعادة البيانات المحلية.',
  'cleared': 'تم المسح',
  'all_data_removed': 'تم حذف كل البيانات المحلية.',
  'settings_reset_message': 'تمت استعادة الإعدادات الافتراضية.',
  'business_profile': 'ملف العمل',
  'saved_invoices_history_message':
      '@count فواتير محفوظة. سيتم إضافة السجل التفصيلي لاحقاً.',
  'invoice_saved_storage': 'تم حفظ الفاتورة في التخزين.',
  'shop_information_saved': 'تم تحديث معلومات المتجر.',
  'customer_information_saved': 'تم حفظ معلومات العميل.',
  'customer_removed_message': 'تم حذف @name.',
  'duplicated': 'تم التكرار',
  'invoice_duplicated_message': 'تم نسخ الفاتورة @number.',
  'deleted': 'تم الحذف',
  'invoice_deleted_message': 'تم حذف الفاتورة @number.',
  'field_required': '@field مطلوب.',
  'this_field': 'هذا الحقل',
  'invalid_email': 'أدخل بريدًا إلكترونيًا صالحًا',
  'invalid_number': 'يجب أن يكون @field رقماً صالحاً',
  'negative_number': 'لا يمكن أن يكون @field سالباً',
  'positive_number': 'يجب أن يكون @field أكبر من صفر',
  'walk_in_customer': 'عميل مباشر',
  'before': 'قبل',
  'after': 'بعد',
  'ar': 'العربية',
  'en': 'الإنجليزية',
  'light': 'فاتح',
  'system': 'النظام',
};
