const Map<String, String> en = {
  'app_name': 'Invoice App',
  'invoices': 'Invoices',
  'create_invoice': 'Create Invoice',
  'customers': 'Customers',
  'shop_info': 'Shop Info',
  'settings': 'Settings',
  'business_settings': 'Business Settings',
  'general_settings': 'General Settings',
  'invoice_settings': 'Invoice Settings',
  'pdf_settings': 'PDF Settings',
  'backup_settings': 'Backup Settings',
  'save_settings': 'Save Settings',
  'business_name': 'Business name',
  'default_currency': 'Default currency',
  'currency_symbol': 'Currency symbol',
  'currency_position': 'Currency position',
  'decimal_digits': 'Decimal digits',
  'language': 'Language',
  'theme_mode': 'Theme mode',
  'invoice_prefix': 'Invoice prefix',
  'starting_invoice_number': 'Starting invoice number',
  'auto_increment_enabled': 'Auto increment enabled',
  'default_tax': 'Default tax %',
  'default_discount': 'Default discount %',
  'notes_template': 'Notes template',
  'payment_instructions': 'Payment instructions',
  'show_logo_pdf': 'Show logo in PDF',
  'show_customer_notes': 'Show customer notes',
  'show_footer': 'Show footer',
  'default_pdf_theme': 'Default PDF theme',
  'paper_size': 'Paper size',
  'font_size_scale': 'Font size scale',
  'compact_mode': 'Compact mode',
  'export_backup': 'Export backup',
  'import_backup': 'Import backup',
  'paste_json_fallback': 'Paste JSON fallback',
  'clear_all_local_data': 'Clear all local data',
  'reset_settings': 'Reset settings',
  'exporting': 'Exporting...',
  'importing': 'Importing...',
  'clearing': 'Clearing...',
  'resetting': 'Resetting...',
  'save_pdf': 'Save PDF',
  'share_pdf': 'Share PDF',
  'print_pdf': 'Print PDF',
  'open_saved_pdf': 'Open saved PDF',
  'modern': 'Modern',
  'minimal': 'Minimal',
  'dark': 'Dark',
  'thermal': 'Thermal',
  'a4': 'A4',
  'cancel': 'Cancel',
  'import': 'Import',
  'open': 'Open',
  'save': 'Save',
  'delete': 'Delete',
  'edit': 'Edit',
  'view': 'View',
  'duplicate': 'Duplicate',
  'change': 'Change',
  'draft': 'Draft',
  'saved': 'Saved',
  'paid': 'Paid',
  'overdue': 'Overdue',
  'cancelled': 'Cancelled',
  'all': 'All',
  'preview': 'Preview',
  'preview_pdf': 'Preview PDF',
  'invoice': 'Invoice',
  'receipt': 'Receipt',
  'customer': 'Customer',
  'customer_name': 'Customer name',
  'full_name': 'Full name',
  'phone': 'Phone',
  'alternative_phone': 'Alternative phone',
  'email': 'Email',
  'address': 'Address',
  'city': 'City',
  'notes': 'Notes',
  'created_date': 'Created date',
  'shop_information': 'Shop information',
  'shop_name': 'Shop name',
  'owner_name': 'Owner name',
  'phone_number': 'Phone number',
  'tax_number': 'Tax number',
  'tax_number_value': 'Tax number: @value',
  'currency': 'Currency',
  'save_shop_information': 'Save shop information',
  'logo_image_path': 'Logo image path',
  'use_placeholder_logo': 'Use placeholder logo',
  'search_customers': 'Search customers',
  'no_customers_yet': 'No customers yet',
  'create_customers_message':
      'Create customers once and reuse them across invoices.',
  'create_customer': 'Create customer',
  'customer_details': 'Customer details',
  'customer_not_found': 'Customer not found',
  'invoice_history': 'Invoice history',
  'save_customer': 'Save customer',
  'new_customer': 'New customer',
  'edit_customer': 'Edit customer',
  'invoice_details': 'Invoice details',
  'invoice_not_found': 'Invoice not found',
  'no_invoices_yet': 'No invoices yet',
  'create_invoice_message': 'Create your first invoice and track it here.',
  'search_invoice_customer': 'Search invoice number or customer',
  'min_price': 'Min price',
  'max_price': 'Max price',
  'number': 'Number',
  'date': 'Date',
  'total': 'Total',
  'status': 'Status',
  'actions': 'Actions',
  'export_pdf': 'Export PDF',
  'subtotal': 'Subtotal',
  'discount': 'Discount',
  'tax': 'Tax',
  'final_total': 'Final total',
  'one_time_customer': 'One-time customer',
  'use_only_invoice': 'Use only in this invoice',
  'create_customer_dialog': 'Create customer',
  'save_permanently': 'Save permanently',
  'product_name': 'Product name',
  'product_image_path': 'Product image path',
  'quantity': 'Quantity',
  'qty': 'Qty',
  'unit_price': 'Unit price',
  'save_product': 'Save product',
  'save_invoice': 'Save invoice',
  'new_invoice': 'New invoice',
  'editing_invoice': 'Editing invoice',
  'invoice_workspace_hint':
      'Build, preview, and export a professional invoice.',
  'business_details_on_invoices':
      'Business details shown on generated invoices',
  'select_customer': 'Select customer',
  'customer_address': 'Customer address',
  'quick_create': 'Quick create',
  'products': 'Products',
  'products_section_hint': 'Add line items with quantities and prices',
  'add_product': 'Add product',
  'no_products': 'No products',
  'add_first_product_message':
      'Add the first product to start building this invoice.',
  'image': 'Image',
  'product': 'Product',
  'edit_product': 'Edit product',
  'delete_product': 'Delete product',
  'invoice_notes': 'Invoice notes',
  'adjustments': 'Adjustments',
  'adjustments_hint': 'Discount and tax update totals live',
  'invoice_totals': 'Invoice totals',
  'live_calculation_summary': 'Live calculation summary',
  'select_customer_dialog': 'Select customer',
  'recent_customers': 'Recent customers',
  'no_matching_customers': 'No matching customers',
  'try_different_customer_search': 'Try another name, phone number, or city.',
  'pdf_preview': 'PDF preview',
  'pdf_preview_title': 'PDF preview - @number',
  'pdf_saved': 'PDF saved',
  'save_invoice_storage_question':
      'Do you want to save this invoice in storage?',
  'do_not_save': 'Do not save',
  'save_invoice_storage': 'Save invoice',
  'no_file': 'No file',
  'save_pdf_first': 'Save the PDF first.',
  'import_backup_json': 'Import backup JSON',
  'paste_backup_json_here': 'Paste backup JSON here',
  'clear_all_local_data_question': 'Clear all local data?',
  'clear_all_local_data_warning':
      'Customers, invoices, shop information, and settings will be deleted.',
  'clear_data': 'Clear data',
  'reset_settings_question': 'Reset settings?',
  'reset_settings_warning': 'Default business settings will be restored.',
  'reset': 'Reset',
  'owner': 'Owner',
  'local_account': 'Local account',
  'clear_search': 'Clear search',
  'billing_workspace': 'Billing workspace',
  'bill_to': 'Bill To',
  'invoice_details_pdf': 'Invoice Details',
  'payment': 'Payment',
  'thank_you': 'Thank you for your business.',
  'page_of': 'Page @page of @pages',
  'save_customer_choice':
      'Save this customer permanently or use only in this invoice?',
  'temporary_customer': 'Temporary customer',
  'temporary_customer_message':
      'Temporary customers can be replaced or saved as new customers.',
  'customer_required': 'Customer information is required.',
  'add_products': 'Add products',
  'product_required': 'At least one invoice product is required.',
  'invoice_saved_message': 'Invoice @number has been saved.',
  'draft_saved': 'Draft saved',
  'draft_saved_message': 'Invoice draft is available locally.',
  'business_settings_saved': 'Business settings have been updated.',
  'export_backup_title': 'Export backup',
  'backup_exported': 'Backup exported',
  'import_backup_title': 'Import backup',
  'backup_imported': 'Backup imported',
  'backup_imported_message': 'Local data has been restored.',
  'cleared': 'Cleared',
  'all_data_removed': 'All local data has been removed.',
  'settings_reset_message': 'Settings restored to defaults.',
  'business_profile': 'Business profile',
  'saved_invoices_history_message':
      '@count saved invoices. Detailed history is coming next.',
  'invoice_saved_storage': 'Invoice was saved in storage.',
  'shop_information_saved': 'Shop information has been updated.',
  'customer_information_saved': 'Customer information has been saved.',
  'customer_removed_message': '@name was removed.',
  'duplicated': 'Duplicated',
  'invoice_duplicated_message': 'Invoice @number copied.',
  'deleted': 'Deleted',
  'invoice_deleted_message': 'Invoice @number was removed.',
  'field_required': '@field is required',
  'this_field': 'This field',
  'invalid_email': 'Enter a valid email address',
  'invalid_number': '@field must be a valid number',
  'negative_number': '@field cannot be negative',
  'positive_number': '@field must be greater than zero',
  'walk_in_customer': 'Walk-in customer',
  'before': 'Before',
  'after': 'After',
  'ar': 'Arabic',
  'en': 'English',
  'light': 'Light',
  'system': 'System',
};
